const mongoose = require('mongoose');

const disputeSchema = new mongoose.Schema(
    {
        job: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Job',
            required: true,
        },
        application: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'Application',
            required: true,
        },
        raisedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        against: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true,
        },
        reason: {
            type: String,
            required: true,
            enum: ['PAYMENT_DELAYED', 'PAYMENT_NOT_GIVEN', 'PARTIAL_PAYMENT', 'EMPLOYER_MISCONDUCT', 'NON_PAYMENT', 'NO_SHOW', 'POOR_WORK', 'LATE_PAYMENT', 'FRAUD', 'HARASSMENT', 'OTHER'],
        },
        description: {
            type: String,
            required: true,
            maxlength: 2000,
        },
        proofs: [String], // Array of URLs to images/docs
        status: {
            type: String,
            enum: ['PENDING', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'OPEN', 'CLOSED', 'ESCALATED'],
            default: 'PENDING',
        },
        priority: {
            type: String,
            enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
            default: 'MEDIUM',
        },
        resolution: {
            type: String,
            enum: ['REFUND_EMPLOYER', 'RELEASE_EMPLOYEE', 'SPLIT', 'DISMISSED', 'PENALTY_APPLIED'],
        },
        adminComments: {
            type: String,
        },
        // Admin action history
        adminActions: [{
            action: String,
            comment: String,
            admin: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
            timestamp: { type: Date, default: Date.now },
        }],
        resolvedAt: {
            type: Date,
        },
        resolvedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User', // Admin
        },
        // Auto-generated dispute indicator
        isAutoGenerated: {
            type: Boolean,
            default: false,
        },
        // Flags for tracking
        isFakeComplaint: {
            type: Boolean,
            default: false,
        },
        // Penalty info
        penaltyApplied: {
            to: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
            amount: Number,
            percentage: Number,
            reason: String,
        },
    },
    {
        timestamps: true,
    }
);

disputeSchema.index({ status: 1, createdAt: -1 });
disputeSchema.index({ raisedBy: 1 });
disputeSchema.index({ against: 1 });

module.exports = mongoose.model('Dispute', disputeSchema);
